version: '3.3'

services:

  nginx:
    image: nginx:1.15.8-alpine
    container_name: metagram-nginx
    ports:
      - 8080:80
    volumes:
      - ./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./etc/nginx/default.template.conf:/etc/nginx/conf.d/default.template
      - php-app:/var/www/html
      - ~/nginx/logs:/var/log/nginx
    environment:
      - NGINX_HOST=${NGINX_HOST}
    links:
      - php
      - mysqldb
    restart: always

  php:
    build:
      context: .
      dockerfile: ./etc/php/Dockerfile
    container_name: metagram-php
    volumes:
      - ./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini
      - php-app:/var/www/html
    links:
      - mysqldb
    restart: always

  composer:
    image: composer:1.8.4
    container_name: metagram-composer
    user: '33'
    volumes:
      - php-app:/var/www/html
    command: install

  mysqldb:
    image: mysql:${MYSQL_VERSION}
    container_name: ${MYSQL_HOST}
    ports:
      - 8989:3306
    env_file:
      - ./.env
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USERNAME}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    restart: always

volumes:
  php-app:
    driver: local
